name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # speeds up installs

      - run: pip install -r requirements.txt -r requirements-dev.txt

      - run: black --check .
      - run: flake8

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - run: pytest -q

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ No npm install; uses a prebuilt action
      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "**/*.md"
          config_file: ".markdownlint.json"
          ignore_files: "node_modules"

  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          path: firmware/esp32
          project-type: sketch
          compliance: permissive
