name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # speeds up installs

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Check formatting (Black)
        run: black --check .

      - name: Run flake8 lint
        run: flake8

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run pytest
        run: pytest -q

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ Markdownlint without Docker/npm global install
      - name: Markdownlint (CLI2)
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
            !node_modules
          config: .markdownlint.json

  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          path: firmware/esp32
          project-type: sketch
          compliance: permissive
